# Mengaktifkan AndroidX dan Jetifier untuk kompatibilitas library modern
android.useAndroidX=true
android.enableJetifier=false

# Alokasi memori JVM (3GB) dan encoding karakter (batas aman 4GB)
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8

# Konfigurasi performa untuk stabilitas build di AndroidIDE
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=3
org.gradle.configureondemand=true

# Menghilangkan peringatan deprecation Java
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Override aapt2 dari Maven untuk mencegah peringatan eksperimental
android.aapt2FromMavenOverride=

# Mengatur level log ke 'warn' agar terminal tidak berisik # debug, lifecycle, info, warn, quiet
org.gradle.logging.level=warn

# Pengaturan otomatis untuk tampilan konsol terminal
org.gradle.console=auto