# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# JVM / Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Stabilitas build AndroidIDE
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.configureondemand=false

# Suppress Java deprecation warnings
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Override server-level aapt2 override to suppress experimental warning
android.aapt2FromMavenOverride=