include ':app'
include ':shared:config'
include ':shared:ui'
include ':shared:color'
include ':shared:preset'
include ':features:clock'
include ':features:fps'
include ':features:network'
include ':features:floating-text'
include ':features:memory'
include ':features:crosshair'
include ':features:battery'
