apply plugin: 'com.android.application'

android {

    namespace = "exp.ftxt"

    compileSdk 35

    defaultConfig {

        applicationId "exp.ftxt"

        minSdk 26
        targetSdk 35

        versionCode 134
        versionName "3.9.3.67.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {

        release {

            minifyEnabled false

            proguardFiles(
                    getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
            )
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:none"
    }

}

task syncDocs(type: Copy) {
    from rootProject.file('README.md')
    from rootProject.file('CHANGELOG.md')
    from rootProject.file('STRUKTUR.md')
    from rootProject.file('PANDUAN.md')
    from rootProject.file('DEVELOPMENT.md')
    from rootProject.file('TENTANG.md')
    into file('src/main/assets')
    rename { name -> name.replace('.md', '.txt') }
}

preBuild.dependsOn syncDocs

dependencies {

    implementation fileTree(
            dir: 'libs',
            include: ['*.jar']
    )

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'com.google.code.gson:gson:2.10.1'

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}