plugins {
    id 'com.android.library'
}

android {
    namespace 'exp.ftxt.features.battery'
    compileSdk 35

    defaultConfig {
        minSdk 26
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':shared:config')
    implementation project(':shared:ui')
    implementation project(':shared:color')
}