plugins {
    id 'com.android.library'
}

android {
    namespace 'exp.ftxt.shared.ui'
    compileSdk 35

    defaultConfig {
        minSdk 26
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':shared:config')
    implementation 'androidx.appcompat:appcompat:1.7.1'
}