name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "-> local.properties:"
          cat local.properties

      - name: Build APK Release
        run: ./gradlew assembleRelease

      - name: Debug — Print APK locations
        run: |
          echo "=== Mencari semua file APK ==="
          find . -type f -name "*.apk" 2>/dev/null
          echo "=== Selesai ==="

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/apk/release/*.apk.idsig
          generate_release_notes: true
